// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFTf9p2y2RYBRBfY68BrkOONeV26ja7sw',
    appId: '1:778523845169:web:366720e53335de2741eb10',
    messagingSenderId: '778523845169',
    projectId: 'iot-water-level-monitori-24dc3',
    authDomain: 'iot-water-level-monitori-24dc3.firebaseapp.com',
    storageBucket: 'iot-water-level-monitori-24dc3.firebasestorage.app',
    measurementId: 'G-L2WVEHHLK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo3t4-XNJyp7mELHQbGuzRz4bhQSmQZcI',
    appId: '1:778523845169:android:9157f60e6e6e8d2841eb10',
    messagingSenderId: '778523845169',
    projectId: 'iot-water-level-monitori-24dc3',
    storageBucket: 'iot-water-level-monitori-24dc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANb0HYNn9GVQ1gu5S9SMorG4xvJ2H2IWc',
    appId: '1:778523845169:ios:3911eb6d488ff59141eb10',
    messagingSenderId: '778523845169',
    projectId: 'iot-water-level-monitori-24dc3',
    storageBucket: 'iot-water-level-monitori-24dc3.firebasestorage.app',
    iosBundleId: 'com.example.iotWaterMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANb0HYNn9GVQ1gu5S9SMorG4xvJ2H2IWc',
    appId: '1:778523845169:ios:3911eb6d488ff59141eb10',
    messagingSenderId: '778523845169',
    projectId: 'iot-water-level-monitori-24dc3',
    storageBucket: 'iot-water-level-monitori-24dc3.firebasestorage.app',
    iosBundleId: 'com.example.iotWaterMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFTf9p2y2RYBRBfY68BrkOONeV26ja7sw',
    appId: '1:778523845169:web:03564734a1bd403b41eb10',
    messagingSenderId: '778523845169',
    projectId: 'iot-water-level-monitori-24dc3',
    authDomain: 'iot-water-level-monitori-24dc3.firebaseapp.com',
    storageBucket: 'iot-water-level-monitori-24dc3.firebasestorage.app',
    measurementId: 'G-R23KBW2GSN',
  );
}
